os:
  - linux
  - osx

sudo: required

language: cpp

before_install:
# see here: https://github.com/numenta/nupic/blob/master/.travis.yml
- "if [ ${TRAVIS_OS_NAME} = 'linux' ]; then . ./ci/travis/before_install-linux.sh; fi"
- "if [ ${TRAVIS_OS_NAME} = 'osx' ]; then . ./ci/travis/before_install-osx.sh; fi"

script:
- "if [ ${TRAVIS_OS_NAME} = 'linux' ]; then . ./ci/travis/script-linux.sh; fi"
- "if [ ${TRAVIS_OS_NAME} = 'osx' ]; then . ./ci/travis/script-osx.sh; fi"

before_deploy:
- "if [ ${TRAVIS_OS_NAME} = 'linux' ]; then . ./ci/travis/before_deploy-linux.sh; fi"

deploy:
  provider: releases
  api_key: $GH_OAUTH_TOKEN
  file_glob: true
  file: "${RELEASE_PKG_FILE}"
  skip_cleanup: true
  on:
    tags: true

env:
  global:
    # GH_OAUTH_TOKEN: Github token > travis encrypt GH_OAUTH_TOKEN=XXXXXX --add
    secure: Ft5430SqJlZycAStoOHYnACvFxE27r/OODgSAfbFSCNAX7ibLL0YV7N5/TzVJiQHmEorUSM3cOVoZRY7h0A7tTfFvL0NUNW3iPjzyi1XzI5Ru6+pKEyCM41MXKiYpq+jC5MtGYoi5oyz0ICd2hICHoOYu0pwXQjopS+gkV1Q9s8GaTgYloANS8zReR6+3zEMw/LfbuUevN37Y4lqcq3kLY7Uhtkogkk66tVt5+5v4ie85JUlMCByDbxkmZjbFtq1lm9/EcCuRKsvc0kW03lZyzTKcqIFgmkZogX7FPK86HNS5RGc6wJ4nmU35XGCXC+DvAHirupOZoLEPsV2pAPBqJd4PY7zPpvBfpq84Kxfdcj9VYK87CNLCnlTQzzSJm7iRjn+4lxx5nRo0aX2ru+d3/1DwA7BTUfBlgOmsb4H65znp4DBL4WjbiH1IqyTHtZ51bGX8l5hVhN9Rg6AYQ22HQh1qmPdvRQyzMyjIE7oeQDOysoPVUcraAPFKN3cv7GYIL9kusxJrKFiYW5MieSNO08nngueLav+sN59DeeImi5H8vwoRv41qI4rvqTcyt4+gOszk4OY1JfZQGlkTvnN9wa35FOJpGy6syQzKvh32TxfRzB6L3rnA8Gb7aBMpWIO4bb/18grNTraQcc0IZBlnWwSHUCmjJiHFznGlQVUFUE=

