os:
  - linux
  - osx

sudo: required

language: cpp

before_install:
- "if [ ${TRAVIS_OS_NAME} = 'linux' ]; then . ./ci/travis/before_install-linux.sh; fi"
- "if [ ${TRAVIS_OS_NAME} = 'osx' ]; then . ./ci/travis/before_install-osx.sh; fi"

script:
- "if [ ${TRAVIS_OS_NAME} = 'linux' ]; then . ./ci/travis/script-linux.sh; fi"
- "if [ ${TRAVIS_OS_NAME} = 'osx' ]; then . ./ci/travis/script-osx.sh; fi"

before_deploy:
- "if [ ${TRAVIS_OS_NAME} = 'linux' ]; then . ./ci/travis/before_deploy-linux.sh; fi"

deploy:
  provider: releases
  # $GH_OAUTH_TOKEN envvar comes from travis-ci web gui
  api_key: $GH_OAUTH_TOKEN
  file_glob: true
  file: "${RELEASE_PKG_FILE}"
  skip_cleanup: true
  on:
    tags: true
