from building import *
import os
import sys


cwd = GetCurrentDir()

src = Glob('*.c')
src += Glob('*.cpp')
src += Glob('../../hbox/hstandalone/hsimplegui/3rdparty/*.c')
src += Glob('../../hbox/hstandalone/hsimplegui/port/*.c')
CPPPATH = [cwd]
CPPPATH += [ cwd+'/../../hbox/hstandalone/hsimplegui/3rdparty/source',cwd+'/../../hbox/hstandalone/hsimplegui/port']

group = DefineGroup('Applications', src, depend = [''], CPPPATH = CPPPATH)

list = os.listdir(cwd)
for item in list:
    if os.path.isfile(os.path.join(cwd, item, 'SConscript')):
        group = group + SConscript(os.path.join(item, 'SConscript'))


if os.path.isfile(os.path.join(cwd+"/../../", 'SConscript')):
    group = group + SConscript(os.path.join(cwd+"/../../", 'SConscript'))

Return('group')
