
if(NOT WIN32)
    set(MATIEC_EXECUTABLE_SUFFIX )
else()
    set(MATIEC_EXECUTABLE_SUFFIX .exe)
endif()
find_program(IEC2C iec2c${MATIEC_EXECUTABLE_SUFFIX} OPTIONAL)
find_program(IEC2IEC iec2iec${MATIEC_EXECUTABLE_SUFFIX} OPTIONAL)
if(NOT "${IEC2C}" STREQUAL "IEC2C-NOTFOUND")
    set(MATIEC_IEC2C_FOUND ON)
    message(STATUS "MATIEC IEC2C:     ${IEC2C}")
else()
    set(MATIEC_IEC2C_FOUND OFF)
endif()
if(NOT "${IEC2IEC}" STREQUAL "IEC2IEC-NOTFOUND")
    set(MATIEC_IEC2IEC_FOUND ON)
    message(STATUS "MATIEC IEC2IEC:   ${IEC2IEC}")
else()
    set(MATIEC_IEC2IEC_FOUND OFF)
endif()
if(IS_DIRECTORY "${CMAKE_CURRENT_LIST_DIR}/../h3rdparty/port/matiec_c_header/" )
    if(NOT DEFINED MATIEC_C_HEADER)
        set(MATIEC_C_HEADER   "${CMAKE_CURRENT_LIST_DIR}/../h3rdparty/port/matiec_c_header/" )
    endif()
endif()
if(NOT DEFINED MATIEC_IEC_HEADER)
    if(IS_DIRECTORY "${CMAKE_CURRENT_LIST_DIR}/../h3rdparty/3rdparty/matiec_c_header/")
        set(MATIEC_IEC_HEADER "${CMAKE_CURRENT_LIST_DIR}/../h3rdparty/3rdparty/matiec_c_header/" )
    endif()
endif()
if(DEFINED MATIEC_IEC_HEADER AND DEFINED MATIEC_C_HEADER)
    set(MATIEC_HEADER_FOUND ON)
    message(STATUS "MATIEC C_HEADER:   ${MATIEC_C_HEADER}")
    message(STATUS "MATIEC IEC_HEADER: ${MATIEC_IEC_HEADER}")
else()
    set(MATIEC_HEADER_FOUND OFF)
endif()


