from building import *
import os
import sys


cwd = GetCurrentDir()

src = Glob('*.c')
src += Glob('*.cpp')
CPPPATH = [cwd]

group = DefineGroup('Applications', src, depend = [''], CPPPATH = CPPPATH)

list = os.listdir(cwd)
for item in list:
    if os.path.isfile(os.path.join(cwd, item, 'SConscript')):
        group = group + SConscript(os.path.join(item, 'SConscript'))


if os.path.isfile(os.path.join(cwd+"/../../", 'SConscript')):
    group = group + SConscript(os.path.join(cwd+"/../../", 'SConscript'))

Return('group')
