/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_MAIN_ENTRY_WITH_ENV_PB_H_INCLUDED
#define PB_MAIN_ENTRY_WITH_ENV_PB_H_INCLUDED
#include H3RDPARTY_NANOPB_PB_HEADER
#include H3RDPARTY_NANOPB_PB_ENCODE_HEADER
#include H3RDPARTY_NANOPB_PB_DECODE_HEADER

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _MainEntryWithEnv {
    int32_t argc;
    pb_callback_t argv;
    pb_callback_t envp;
} MainEntryWithEnv;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define MainEntryWithEnv_init_default            {0, {{NULL}, NULL}, {{NULL}, NULL}}
#define MainEntryWithEnv_init_zero               {0, {{NULL}, NULL}, {{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define MainEntryWithEnv_argc_tag                1
#define MainEntryWithEnv_argv_tag                2
#define MainEntryWithEnv_envp_tag                3

/* Struct field encoding specification for nanopb */
#define MainEntryWithEnv_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    argc,              1) \
X(a, CALLBACK, REPEATED, STRING,   argv,              2) \
X(a, CALLBACK, REPEATED, STRING,   envp,              3)
#define MainEntryWithEnv_CALLBACK pb_default_field_callback
#define MainEntryWithEnv_DEFAULT NULL

extern const pb_msgdesc_t MainEntryWithEnv_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define MainEntryWithEnv_fields &MainEntryWithEnv_msg

/* Maximum encoded size of messages (where known) */
/* MainEntryWithEnv_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
