/* DO NOT EDIT,AUTO GENERATED BY hcrctablegenerate */
#ifndef __HCRC_CRC16_XMODEM_H__
#define __HCRC_CRC16_XMODEM_H__
#include "stdint.h"
#include "stdbool.h"
#include "stdlib.h"
#ifdef __cplusplus
extern "C"
{
#endif
#define HCRC_CRC16_XMODEM 1
uint16_t hcrc_crc16_xmodem_table_starts(void);
uint16_t hcrc_crc16_xmodem_table_update(uint16_t ctx,const uint8_t *data,size_t datalen);
uint16_t hcrc_crc16_xmodem_table_finish(uint16_t ctx);
uint16_t hcrc_crc16_xmodem_table_calculate(const uint8_t *data,size_t datalen);
bool     hcrc_crc16_xmodem_table_check(const uint8_t *data,size_t datalen,uint16_t check);
#ifdef __cplusplus
}
#endif
#endif
