/* DO NOT EDIT,AUTO GENERATED BY hcrctablegenerate */
#ifndef __HCRC_CRC8_ROHC_H__
#define __HCRC_CRC8_ROHC_H__
#include "stdint.h"
#include "stdbool.h"
#include "stdlib.h"
#ifdef __cplusplus
extern "C"
{
#endif
#define HCRC_CRC8_ROHC 1
uint8_t hcrc_crc8_rohc_table_starts(void);
uint8_t hcrc_crc8_rohc_table_update(uint8_t ctx,const uint8_t *data,size_t datalen);
uint8_t hcrc_crc8_rohc_table_finish(uint8_t ctx);
uint8_t hcrc_crc8_rohc_table_calculate(const uint8_t *data,size_t datalen);
bool    hcrc_crc8_rohc_table_check(const uint8_t *data,size_t datalen,uint8_t check);
#ifdef __cplusplus
}
#endif
#endif
