/* DO NOT EDIT,AUTO GENERATED BY hcrctablegenerate */
#ifndef __HCRC_CRC64_DEFAULT_H__
#define __HCRC_CRC64_DEFAULT_H__
#include "stdint.h"
#include "stdbool.h"
#include "stdlib.h"
#ifdef __cplusplus
extern "C"
{
#endif
#define HCRC_CRC64_DEFAULT 1
uint64_t hcrc_crc64_default_table_starts(void);
uint64_t hcrc_crc64_default_table_update(uint64_t ctx,const uint8_t *data,size_t datalen);
uint64_t hcrc_crc64_default_table_finish(uint64_t ctx);
uint64_t hcrc_crc64_default_table_calculate(const uint8_t *data,size_t datalen);
bool     hcrc_crc64_default_table_check(const uint8_t *data,size_t datalen,uint64_t check);
#ifdef __cplusplus
}
#endif
#endif
