/* DO NOT EDIT,AUTO GENERATED BY hcrctablegenerate */
#ifndef __HCRC_CRC32_CKSUM_H__
#define __HCRC_CRC32_CKSUM_H__
#include "stdint.h"
#include "stdbool.h"
#include "stdlib.h"
#ifdef __cplusplus
extern "C"
{
#endif
#define HCRC_CRC32_CKSUM 1
uint32_t hcrc_crc32_cksum_table_starts(void);
uint32_t hcrc_crc32_cksum_table_update(uint32_t ctx,const uint8_t *data,size_t datalen);
uint32_t hcrc_crc32_cksum_table_finish(uint32_t ctx);
uint32_t hcrc_crc32_cksum_table_calculate(const uint8_t *data,size_t datalen);
bool     hcrc_crc32_cksum_table_check(const uint8_t *data,size_t datalen,uint32_t check);
#ifdef __cplusplus
}
#endif
#endif
