#ifndef __PROJECT_VERSION_H__
#define __PROJECT_VERSION_H__

#define PROJECT_MAJOR_VERSION 0

#define PROJECT_MINOR_VERSION 5

#define PROJECT_REVISION_VERSION 0

#define PROJECT_BUILD_VERSION 19397

#define PROJECT_VERSION_STR "0.5.0.19397"

#endif
